### PR TITLE
Remove webpack from node dependencies

### PR DESCRIPTION
**Pull request by adambraimbridge**
To test this, I ran `make clean install build` and  `make clean install build-production` for both the `master` and the `remove-webpack` branch.

After each build, I moved the `/public/` directory into another folder.

image

Above: For both `build` and `build-production`, the generated `/public/` content is identical. Except for timestamps in `__about.json`.

### CODE REVIEW

**Comment by wheresrhys** [comment]
actually, you probably still need bower in your dependencies

**Comment by adambraimbridge** [comment]
Thanks. Yeah, it was still working for me because I had bower installed globally. I've uninstalled it from my machine so that it's more like CircleCI environments.

**Comment by adambraimbridge** [comment]
Cool, it's passing CI now. @adgad, cool if I deploy this, or is Friday afternoon a bit risky ..?

**Comment by adambraimbridge** [comment]
Verbal 👍 from @adgad :)  I'll merge this on Monday.

**Pull request merged**
